"""
streamforge/exporters/flink_ddl.py — Apache Flink SQL DDL Exporter
====================================================================

Converts an InferredSchema to a Flink SQL CREATE TABLE statement.

Flink SQL type mapping:
  STRING/UUID/EMAIL/PHONE → STRING
  INTEGER → BIGINT
  FLOAT   → DOUBLE
  BOOLEAN → BOOLEAN
  TIMESTAMP_EPOCH_MS   → TIMESTAMP(3) METADATA FROM 'timestamp' + WATERMARK
  TIMESTAMP_ISO8601    → TIMESTAMP(3)
  TIMESTAMP_RFC2822    → STRING (no native RFC 2822 in Flink)
  DATE    → DATE
  ARRAY   → ARRAY<STRING>
  OBJECT  → ROW<...> (simplified — dot-notation fields merged)
  MIXED   → STRING (safe fallback)
  NULL    → STRING (safe fallback)

Reference: https://nightlies.apache.org/flink/flink-docs-stable/docs/dev/table/types/
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..models import InferredSchema

from ..models import FieldType

logger = logging.getLogger(__name__)

# Flink SQL type mapping
_FLINK_TYPES: dict[FieldType, str] = {
    FieldType.STRING:              "STRING",
    FieldType.UUID:                "STRING",
    FieldType.EMAIL:               "STRING",
    FieldType.PHONE:               "STRING",
    FieldType.INTEGER:             "BIGINT",
    FieldType.FLOAT:               "DOUBLE",
    FieldType.BOOLEAN:             "BOOLEAN",
    FieldType.TIMESTAMP_ISO8601:   "TIMESTAMP(3)",
    FieldType.TIMESTAMP_RFC2822:   "STRING",
    FieldType.DATE:                "DATE",
    FieldType.ARRAY:               "ARRAY<STRING>",
    FieldType.OBJECT:              "ROW<>",
    FieldType.MIXED:               "STRING",
    FieldType.NULL:                "STRING",
}


def _flink_type(field_type: FieldType, nullable: bool) -> str:
    base = _FLINK_TYPES.get(field_type, "STRING")
    # TIMESTAMP_EPOCH_MS is handled specially (becomes metadata column)
    if nullable and field_type not in (FieldType.MIXED, FieldType.NULL):
        return base
    return base


def _safe_col(name: str) -> str:
    """Backtick-quote column names that are SQL reserved words or contain dots."""
    reserved = {
        "timestamp", "time", "date", "value", "key", "offset", "table",
        "select", "from", "where", "order", "group", "join", "type",
    }
    if name.lower() in reserved or "." in name or "-" in name:
        return f"`{name}`"
    return name


def schema_to_flink_ddl(
    schema: InferredSchema,
    brokers: list[str] | None = None,
    topic: str | None = None,
) -> str:
    """
    Convert an InferredSchema to a Flink SQL CREATE TABLE statement.

    Args:
        schema:  The schema to export.
        brokers: Kafka broker list for the WITH clause (optional).
        topic:   Kafka topic name. Defaults to schema.stream_name.

    Returns:
        Flink SQL DDL string.
    """
    kafka_topic = topic or schema.stream_name
    table_name = schema.stream_name.replace(".", "_").replace("-", "_")
    broker_str = ",".join(brokers) if brokers else "localhost:9092"

    # Separate epoch timestamp fields — they become METADATA columns
    epoch_ts_fields = [
        f for f in schema.fields
        if f.field_type == FieldType.TIMESTAMP_EPOCH_MS
    ]
    regular_fields = [
        f for f in schema.fields
        if f.field_type != FieldType.TIMESTAMP_EPOCH_MS
    ]

    lines: list[str] = []

    # Header comment
    lines.extend([
        "-- Generated by StreamForge",
        f"-- Source: kafka://{kafka_topic}  Schema: v{schema.version}",
        f"-- Fields: {len(schema.fields)}  Confidence: {schema.inference_confidence:.0%}",
        f"-- Inferred: {schema.inferred_at[:10]}",
        "",
        f"CREATE TABLE {table_name} (",
    ])

    col_defs: list[str] = []

    # Regular (non-timestamp-epoch) fields
    for field in regular_fields:
        col_name = _safe_col(field.path.replace(".", "_"))
        flink_type = _flink_type(field.field_type, field.nullable)
        nullable_str = "" if field.required and not field.nullable else " NULL"
        comment = ""
        if field.notes:
            safe_notes = field.notes.replace("'", "''")[:120]
            comment = f" COMMENT '{safe_notes}'"
        col_defs.append(f"    {col_name:<32}{flink_type}{nullable_str}{comment}")

    # Epoch timestamp as METADATA column (reads directly from Kafka message timestamp)
    for ts_field in epoch_ts_fields:
        col_name = _safe_col(ts_field.path.replace(".", "_"))
        col_defs.append(
            f"    {col_name:<32}TIMESTAMP(3) METADATA FROM 'timestamp' VIRTUAL"
        )

    # Add WATERMARK if we have any timestamp fields
    if epoch_ts_fields:
        first_ts = _safe_col(epoch_ts_fields[0].path.replace(".", "_"))
        col_defs.append(f"    WATERMARK FOR {first_ts} AS {first_ts} - INTERVAL '5' SECOND")
    elif any(f.field_type == FieldType.TIMESTAMP_ISO8601 for f in regular_fields):
        ts_field = next(f for f in regular_fields if f.field_type == FieldType.TIMESTAMP_ISO8601)
        ts_col = _safe_col(ts_field.path.replace(".", "_"))
        col_defs.append(f"    WATERMARK FOR {ts_col} AS {ts_col} - INTERVAL '5' SECOND")

    lines.append(",\n".join(col_defs))
    lines.extend([
        ") WITH (",
        "    'connector'                          = 'kafka',",
        f"    'topic'                              = '{kafka_topic}',",
        f"    'properties.bootstrap.servers'       = '{broker_str}',",
        "    'properties.group.id'                = 'streamforge-flink',",
        "    'scan.startup.mode'                  = 'earliest-offset',",
        "    'format'                             = 'json',",
        "    'json.ignore-parse-errors'           = 'true',",
        "    'json.timestamp-format.standard'     = 'ISO-8601'",
        ");",
    ])

    return "\n".join(lines)
