"""
streamforge/exporters/ksqldb.py — ksqlDB CREATE STREAM Exporter
================================================================

Converts an InferredSchema to a ksqlDB CREATE STREAM statement.

ksqlDB type mapping:
  STRING/UUID/EMAIL/PHONE → VARCHAR
  INTEGER → BIGINT
  FLOAT   → DOUBLE
  BOOLEAN → BOOLEAN
  TIMESTAMP_EPOCH_MS   → BIGINT  (epoch ms — use AS_TIMESTAMP() in queries)
  TIMESTAMP_ISO8601    → VARCHAR (parse with PARSE_TIMESTAMP)
  TIMESTAMP_RFC2822    → VARCHAR
  DATE    → DATE
  ARRAY   → ARRAY<VARCHAR>
  OBJECT  → STRUCT<...>
  MIXED   → VARCHAR (safe fallback)
  NULL    → VARCHAR

Reference: https://docs.ksqldb.io/en/latest/reference/sql/data-definition/
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..models import InferredSchema

from ..models import FieldType

logger = logging.getLogger(__name__)

_KSQL_TYPES: dict[FieldType, str] = {
    FieldType.STRING:              "VARCHAR",
    FieldType.UUID:                "VARCHAR",
    FieldType.EMAIL:               "VARCHAR",
    FieldType.PHONE:               "VARCHAR",
    FieldType.INTEGER:             "BIGINT",
    FieldType.FLOAT:               "DOUBLE",
    FieldType.BOOLEAN:             "BOOLEAN",
    FieldType.TIMESTAMP_EPOCH_MS:  "BIGINT",
    FieldType.TIMESTAMP_ISO8601:   "VARCHAR",
    FieldType.TIMESTAMP_RFC2822:   "VARCHAR",
    FieldType.DATE:                "DATE",
    FieldType.ARRAY:               "ARRAY<VARCHAR>",
    FieldType.OBJECT:              "STRUCT<>",
    FieldType.MIXED:               "VARCHAR",
    FieldType.NULL:                "VARCHAR",
}


def schema_to_ksqldb(
    schema: InferredSchema,
    topic: str | None = None,
    value_format: str = "JSON",
) -> str:
    """
    Convert an InferredSchema to a ksqlDB CREATE STREAM statement.

    Args:
        schema:       The schema to export.
        topic:        Kafka topic name. Defaults to schema.stream_name.
        value_format: Serialisation format (JSON, AVRO, PROTOBUF). Default: JSON.

    Returns:
        ksqlDB DDL string.
    """
    kafka_topic = topic or schema.stream_name
    stream_name = schema.stream_name.replace(".", "_").replace("-", "_").upper()

    # Identify potential key field (look for *_id, uuid, or first field)
    key_field = None
    for candidate in ("event_id", "id", "message_id", "record_id"):
        if any(f.path == candidate for f in schema.fields):
            key_field = candidate
            break

    # Detect timestamp field for TIMESTAMP / TIMESTAMP_FORMAT options
    ts_field = next(
        (f for f in schema.fields if f.field_type in (
            FieldType.TIMESTAMP_EPOCH_MS, FieldType.TIMESTAMP_ISO8601
        )),
        None,
    )

    lines: list[str] = [
        "-- Generated by StreamForge",
        f"-- Source: kafka://{kafka_topic}  Schema: v{schema.version}",
        f"-- Fields: {len(schema.fields)}  Confidence: {schema.inference_confidence:.0%}",
        "",
        f"CREATE STREAM {stream_name} (",
    ]

    col_defs: list[str] = []
    for field in schema.fields:
        col_name = field.path.replace(".", "_").upper()
        ksql_type = _KSQL_TYPES.get(field.field_type, "VARCHAR")
        key_suffix = " KEY" if field.path == key_field else ""
        col_defs.append(f"    {col_name:<32}{ksql_type}{key_suffix}")

    lines.append(",\n".join(col_defs))
    lines.append(") WITH (")

    with_clauses = [
        f"    KAFKA_TOPIC='{kafka_topic}',",
        f"    VALUE_FORMAT='{value_format}',",
        "    PARTITIONS=1",
    ]
    if ts_field:
        ts_col = ts_field.path.replace(".", "_").upper()
        if ts_field.field_type == FieldType.TIMESTAMP_EPOCH_MS:
            with_clauses.insert(-1, f"    TIMESTAMP='{ts_col}',")
        elif ts_field.field_type == FieldType.TIMESTAMP_ISO8601:
            with_clauses.insert(-1, f"    TIMESTAMP='{ts_col}',")
            with_clauses.insert(-1, "    TIMESTAMP_FORMAT='yyyy-MM-dd''T''HH:mm:ss.SSSZ',")

    lines.extend(with_clauses)
    lines.append(");")

    # Add a helpful query example
    lines.extend([
        "",
        "-- Example: select all events",
        f"-- SELECT * FROM {stream_name} EMIT CHANGES;",
    ])
    if ts_field and ts_field.field_type == FieldType.TIMESTAMP_EPOCH_MS:
        ts_col = ts_field.path.replace(".", "_").upper()
        lines.append(
            f"-- SELECT *, TIMESTAMPTOSTRING({ts_col}, 'yyyy-MM-dd HH:mm:ss') AS ts_str "
            f"FROM {stream_name} EMIT CHANGES;"
        )

    return "\n".join(lines)
