"""Markdown data dictionary exporter.

Produces a one-page, human-readable data dictionary that consumers
can read without understanding YAML, JSON Schema, or Avro.

Designed for: Slack posts, wiki pages, onboarding docs, data catalog entries.
"""

from __future__ import annotations

from ..models import InferredSchema


def schema_to_markdown(schema: InferredSchema) -> str:
    """Convert an InferredSchema to a Markdown data dictionary.

    Output format:
        # stream_name — Data Dictionary
        Version | Confidence | Events sampled | Last updated

        | Field | Type | Required | Values / Range | PII |
        |-------|------|----------|----------------|-----|
        ...
    """
    lines = [
        f"# {schema.stream_name} — Data Dictionary",
        "",
        f"**Version:** {schema.version}  ",
        f"**Confidence:** {schema.inference_confidence:.0%}  ",
        f"**Events sampled:** {schema.event_count_sampled}  ",
        f"**Last updated:** {schema.inferred_at[:10]}  ",
        f"**Model:** {schema.inference_model}  ",
        "",
    ]

    if schema.top_level_event_types:
        lines.append(f"**Event types:** {', '.join(schema.top_level_event_types)}")
        lines.append("")

    # Field table
    lines.append("| Field | Type | Required | Values / Range | PII |")
    lines.append("|-------|------|----------|----------------|-----|")

    for f in schema.fields:
        # Type
        ftype = f.field_type.value

        # Required
        req = "yes" if f.required else "no"
        if f.nullable:
            req += " (nullable)"

        # Values / Range
        val_parts = []
        if f.enum_values:
            if len(f.enum_values) <= 10:
                val_parts.append(", ".join(f.enum_values))
            else:
                val_parts.append(f"{', '.join(f.enum_values[:8])}, ... (+{len(f.enum_values) - 8})")

        if f.value_stats:
            vs = f.value_stats
            if "min" in vs and "max" in vs:
                val_parts.append(f"{vs['min']} — {vs['max']}")
            if "distribution" in vs:
                top3 = sorted(vs["distribution"].items(), key=lambda x: -x[1])[:3]
                dist_str = ", ".join(f"{k}: {v:.0%}" for k, v in top3)
                val_parts.append(dist_str)
            if "cardinality" in vs and not f.enum_values:
                val_parts.append(f"{vs['cardinality']} distinct")

        values = " | ".join(val_parts) if val_parts else "—"

        # PII
        pii = ", ".join(p.value for p in f.pii_categories) if f.pii_categories else "—"

        lines.append(f"| {f.path} | {ftype} | {req} | {values} | {pii} |")

    # PII summary
    pii_fields = [f for f in schema.fields if f.pii_categories]
    if pii_fields:
        lines.append("")
        lines.append("### PII Fields")
        lines.append("")
        for f in pii_fields:
            cats = ", ".join(p.value for p in f.pii_categories)
            lines.append(f"- **{f.path}** — {cats}")

    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by StreamForge v{schema.version}*")

    return "\n".join(lines)
