"""
streamforge/exporters/protobuf.py — Protocol Buffers (proto3) Exporter
=======================================================================

Converts an InferredSchema to a proto3 .proto file.

Type mapping:
  STRING/UUID/EMAIL/PHONE → string
  INTEGER → int64
  FLOAT   → double
  BOOLEAN → bool
  TIMESTAMP_EPOCH_MS   → google.protobuf.Timestamp (import added)
  TIMESTAMP_ISO8601    → google.protobuf.Timestamp (import added)
  TIMESTAMP_RFC2822    → string
  DATE    → string  (no native date type in proto3; use string with format annotation)
  ARRAY   → repeated string
  OBJECT  → nested message (simplified — dot-notation fields only)
  MIXED   → bytes  (opaque fallback for truly polymorphic fields)
  NULL    → bytes  (opaque fallback)

Field numbers are assigned in definition order (required fields first, then optional;
within each group, sorted alphabetically by path for wire-format stability).

Reference: https://developers.google.com/protocol-buffers/docs/proto3
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..models import InferredSchema

from ..models import FieldType

logger = logging.getLogger(__name__)

_PROTO_TYPES: dict[FieldType, str] = {
    FieldType.STRING:            "string",
    FieldType.UUID:              "string",
    FieldType.EMAIL:             "string",
    FieldType.PHONE:             "string",
    FieldType.INTEGER:           "int64",
    FieldType.FLOAT:             "double",
    FieldType.BOOLEAN:           "bool",
    FieldType.TIMESTAMP_RFC2822: "string",
    FieldType.DATE:              "string",
    FieldType.OBJECT:            "bytes",
    FieldType.MIXED:             "bytes",
    FieldType.NULL:              "bytes",
}

_TIMESTAMP_TYPES = {FieldType.TIMESTAMP_EPOCH_MS, FieldType.TIMESTAMP_ISO8601}


def schema_to_proto(schema: InferredSchema) -> str:
    """
    Convert an InferredSchema to a proto3 schema file.

    Returns:
        Proto3 .proto file contents as a string.
    """
    needs_timestamp_import = any(
        f.field_type in _TIMESTAMP_TYPES for f in schema.fields
    )

    # Derive a valid proto message name (PascalCase, no dots)
    msg_name = _to_pascal_case(schema.stream_name)

    # Build field definitions: required fields first, then optional.
    # Within each group, sort alphabetically by path to guarantee stable
    # field numbers across schema versions (presence_rate may change).
    required_fields = sorted(
        [f for f in schema.fields if f.required],
        key=lambda f: f.path,
    )
    optional_fields = sorted(
        [f for f in schema.fields if not f.required],
        key=lambda f: f.path,
    )
    ordered = required_fields + optional_fields

    lines: list[str] = [
        "// Generated by StreamForge",
        f"// Source: {schema.stream_name}  Schema: v{schema.version}",
        f"// Fields: {len(schema.fields)}  Confidence: {schema.inference_confidence:.0%}",
        f"// Inferred: {schema.inferred_at[:10]}",
        "",
        'syntax = "proto3";',
        "",
        'package io.streamforge.events;',
        "",
    ]

    if needs_timestamp_import:
        lines.append('import "google/protobuf/timestamp.proto";')
        lines.append("")

    lines.append(f"message {msg_name} {{")

    for i, field in enumerate(ordered, start=1):
        field_name = field.path.replace(".", "_")
        proto_type = _proto_type(field)
        is_repeated = field.field_type == FieldType.ARRAY
        repeated_prefix = "repeated " if is_repeated else ""

        comment_parts: list[str] = []
        if not field.required:
            comment_parts.append("optional")
        if field.pii_categories:
            pii_str = ", ".join(p.value for p in field.pii_categories)
            comment_parts.append(f"PII:{pii_str}")
        if field.notes:
            comment_parts.append(field.notes[:80])
        comment = f"  // {' | '.join(comment_parts)}" if comment_parts else ""

        lines.append(f"    {repeated_prefix}{proto_type} {field_name} = {i};{comment}")

    lines.append("}")
    return "\n".join(lines)


def _proto_type(field) -> str:  # type: ignore[no-untyped-def]
    if field.field_type in _TIMESTAMP_TYPES:
        return "google.protobuf.Timestamp"
    if field.field_type == FieldType.ARRAY:
        return "string"  # repeated string; items are repeated, not the array
    return _PROTO_TYPES.get(field.field_type, "string")


def _to_pascal_case(name: str) -> str:
    """Convert stream name (e.g. 'events.payments') to PascalCase message name."""
    parts = name.replace("-", ".").replace("_", ".").split(".")
    return "".join(p.capitalize() for p in parts if p) or "Schema"
