-- Generated by StreamForge
-- Source: kafka://events.payments  Schema: v1.0.0
-- Fields: 9  Confidence: 60%
-- Inferred: 2026-03-19

CREATE TABLE events_payments (
    event_id                        STRING COMMENT 'Statistically inferred (LLM fallback)',
    event_type                      STRING COMMENT 'Statistically inferred (LLM fallback)',
    user_id                         STRING COMMENT 'Statistically inferred (LLM fallback)',
    merchant                        STRING COMMENT 'Statistically inferred (LLM fallback)',
    currency                        STRING COMMENT 'Statistically inferred (LLM fallback)',
    status                          STRING COMMENT 'Statistically inferred (LLM fallback)',
    amount                          DOUBLE COMMENT 'Statistically inferred (LLM fallback)',
    `timestamp`                     BIGINT COMMENT 'Statistically inferred (LLM fallback)',
    user_email                      STRING NULL COMMENT 'Statistically inferred (LLM fallback)'
) WITH (
    'connector'                          = 'kafka',
    'topic'                              = 'events.payments',
    'properties.bootstrap.servers'       = 'localhost:9092',
    'properties.group.id'                = 'streamforge-flink',
    'scan.startup.mode'                  = 'earliest-offset',
    'format'                             = 'json',
    'json.ignore-parse-errors'           = 'true',
    'json.timestamp-format.standard'     = 'ISO-8601'
);